sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8d17910c8f3a_key -iv $encrypted_8d17910c8f3a_iv
  -in sa.json.enc -out sa.json -d
- docker build -f Dockerfile.dev -t andgandolfi/docker-react-dev .
script:
- docker run -e CI=true andgandolfi/docker-react-dev npm run test
deploy:
  provider: gae
  project: "gandolfi"
  keyfile: "sa.json"
  on:
    branch: master
